# Default values for grafana-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

region: "qa-de-1"

image:
  registry: keppel.eu-de-1.cloud.sap/ccloud
  pullPolicy: ""
  tag: "20201005083839"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: grafana-operator

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

prometheus: infra-frontend

record: {}

openstack: {}

grafana:
  image:
    tag: v7.0.x

apiserver: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
