apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-operator.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "grafana-operator.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/targets: {{ .Values.prometheus | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "grafana-operator.selectorLabels" . | nindent 4 }}
