{
 "title": "GaaS CPU Mem Disk",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n### cpu / memory / disk information\n\n\n\n"
  },
  {
   "title": "cpu usage by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_cpu_usage_average/100)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "memory usage by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_mem_usage_average/100)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "disk read by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_virtualDisk_read_average)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "disk write by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_virtualDisk_write_average)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  }
 ]
}