{
 "title": "GaaS Load Balancer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n### load balancer information\n\n\n\n"
  },
  {
   "title": "number of current connections by load balancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "snmp_f5_ltmVirtualServStatClientCurConns",
     "legendFormat": "{{lb_id}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "number of connections/sec by load balancer (avg last 5min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "ceil(rate(snmp_f5_ltmVirtualServStatClientCurConns{}[5m]))",
     "legendFormat": "{{lb_id}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "network traffic in by load balancer (avg last 5min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "rate(snmp_f5_ltmVirtualServStatClientBytesIn{}[5m])",
     "legendFormat": "{{lb_id}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "network traffic out by load balancer (avg last 5min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "rate(snmp_f5_ltmVirtualServStatClientBytesOut{}[5m])",
     "legendFormat": "{{lb_id}}",
     "period": "300"
    }
   ]
  }
 ]
}