{
 "title": "GaaS Network",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n### network information\n\n\n"
  },
  {
   "title": "network traffic received by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_net_bytesRx_average)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "network traffic sent by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_net_bytesTx_average)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "network dropped received packets by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_net_droppedRx_summation)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  },
  {
   "title": "network dropped sent packets by instance name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "error": "No metric specified",
     "expr": "sum(vcenter_net_droppedTx_summation)  by (vmware_name)",
     "legendFormat": "{{vmware_name}}",
     "period": "300"
    }
   ]
  }
 ]
}