package model

const (
	GrafanaImage                        = "keppel.eu-de-1.cloud.sap/ccloud/grafana"
	GrafanaVersion                      = "6.5.12"
	GrafanaProxyImage                   = "keppel.eu-de-1.cloud.sap/ccloud/dex"
	GrafanaProxyVersion                 = "8373c31b3e2d96ad3a7313227aa1bb8c59ddca39"
	GrafanaServiceAccountName           = "grafana-serviceaccount"
	GrafanaProxyServiceAccountName      = "grafana-dex"
	GrafanaServiceName                  = "grafana-service"
	GrafanaProxyServiceName             = "grafana-proxy-service"
	GrafanaConfigName                   = "grafana-config"
	GrafanaProxyConfigName              = "grafana-proxy-config"
	GrafanaConfigFileName               = "grafana.ini"
	GrafanaProxyConfigFileName          = "config.yaml"
	GrafanaIngressName                  = "grafana-ingress"
	GrafanaProxyIngressName             = "grafana-proxy-ingress"
	GrafanaProxyRoleBindingName         = "grafana-proxy-rolebinding"
	GrafanaRouteName                    = "grafana-route"
	GrafanaDeploymentName               = "grafana-deployment"
	GrafanaProxyDeploymentName          = "grafana-proxy-deployment"
	GrafanaPluginsVolumeName            = "grafana-plugins"
	GrafanaInitContainerName            = "grafana-plugins-init"
	GrafanaLogsVolumeName               = "grafana-logs"
	GrafanaDataVolumeName               = "grafana-data"
	GrafanaDatasourcesConfigMapName     = "grafana-datasources"
	GrafanaHealthEndpoint               = "/api/health"
	GrafanaProxyHealthEndpoint          = "/keys"
	GrafanaPodLabel                     = "grafana"
	GrafanaProxyPodLabel                = "grafana-proxy"
	LastConfigAnnotation                = "last-config"
	LastConfigEnvVar                    = "LAST_CONFIG"
	LastDatasourcesConfigEnvVar         = "LAST_DATASOURCES"
	GrafanaAdminSecretName              = "grafana-admin-credentials"
	DefaultAdminUser                    = "admin"
	GrafanaAdminUserEnvVar              = "GF_SECURITY_ADMIN_USER"
	GrafanaAdminPasswordEnvVar          = "GF_SECURITY_ADMIN_PASSWORD"
	GrafanaHttpPort                 int = 3000
	GrafanaHttpPortName                 = "grafana"
)
